### ISSUE TITLE
Enable support for keystone V3 authentication

### ISSUE THREAD

**Issue by RGLin** [javaswift/joss#133]
I tried:

[Account account = new AccountFactory()
	    .setUsername(username)
	    .setPassword(password)
	    .setAuthUrl("url/v3/")
	    .setTenantName(TenantName)
	    .createAccount();](url)

But it returns:

[Exception in thread "main" Command exception, HTTP Status code: 400 => UNKNOWN
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.verifyCode(HttpStatusChecker.java:45)
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:50)
	at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
	at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
	at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
	at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
	at Test.main(Test.java:14)](url)

**Comment by singhsimranjot** [comment]
Hi @ferrys 
I'm getting the same error on v1. Does it support v1.0?

**Comment by ferrys** [comment]
Hi @singhsimranjot, v1 auth should be supported.
