### ISSUE TITLE
KeystoneV3 authentication fails with nullpointer exeception

### ISSUE THREAD

**Issue by breddy-nnk** [javaswift/joss#166]
Hi ,
I am using latest version of joss 0.10.2 to authenticate using KeystoneV3Authentication. while processing the authentication response, It is throwing null-pointer exception as shown below.
Exception occurred while initializing: : java.lang.NullPointerException
	at org.javaswift.joss.command.shared.identity.access.KeystoneV3Access.getEndPoints(KeystoneV3Access.java:89) [joss-0.10.2.jar:]
	at org.javaswift.joss.command.shared.identity.access.KeystoneV3Access.<init>(KeystoneV3Access.java:20) [joss-0.10.2.jar:]
	at org.javaswift.joss.command.impl.identity.KeystoneAuthenticationV3CommandImpl.getReturnObject(KeystoneAuthenticationV3CommandImpl.java:60) [joss-0.10.2.jar:]
	at org.javaswift.joss.command.impl.identity.KeystoneAuthenticationV3CommandImpl.getReturnObject(KeystoneAuthenticationV3CommandImpl.java:24) [joss-0.10.2.jar:]
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51) [joss-0.10.2.jar:]
	at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:110) [joss-0.10.2.jar:]
	at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:25) [joss-0.10.2.jar:]
	at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35) [joss-0.10.2.jar:]
	at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30) [joss-0.10.2.jar:]
	at net.juniper.jnap.provider.csp.swift.SwiftClient.<init>(SwiftClient.java:71) [csp-provider-impl-v1.jar:]

Is this a known issue or  am I missing something?
Request body:
{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "name": "admin",
          "password": "t5rcH7ZDyjlETy3",
          "domain": {
            "name": "Default"
          }
        }
      }
    }
  }
}
Response body:
{
  "token": {
    "issued_at": "2019-05-13T05:59:54.000000Z",
    "audit_ids": [
      "jeg_jQrESKGHvdFltUqHSA"
    ],
    "methods": [
      "password"
    ],
    "expires_at": "2019-05-13T08:59:54.000000Z",
    "user": {
      "password_expires_at": "2019-05-10T11:35:12.201748",
      "domain": {
        "id": "default",
        "name": "Default"
      },
      "id": "4fa37695552a4856ac12ee9731dedd8f",
      "name": "admin"
    }
  }
}

**Comment by breddy-nnk** [comment]
verified with latest master code (0.10.3) and it is working fine
