### ISSUE TITLE
AccountFactory NullPointerException

### ISSUE THREAD

**Issue by SirWellington** [javaswift/joss#75]
I'm getting a null pointer exception when trying to create an account in code.

``` java
Account account = new AccountFactory()
                    .setUsername(username)
                    .setPassword(password)
                    .setPublicHost(url)
                    .setAuthUrl(authUrl)
                    .setTenantName(tenantName)
                    .createAccount();
```

This is the exception seen

``` java
java.lang.NullPointerException
    at org.javaswift.joss.command.impl.identity.KeystoneAuthenticationCommandImpl.getReturnObject(KeystoneAuthenticationCommandImpl.java:58)
    at org.javaswift.joss.command.impl.identity.KeystoneAuthenticationCommandImpl.getReturnObject(KeystoneAuthenticationCommandImpl.java:21)
    at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:51)
    at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:98)
    at org.javaswift.joss.client.impl.ClientImpl.createAccount(ClientImpl.java:27)
    at org.javaswift.joss.client.core.AbstractClient.authenticate(AbstractClient.java:35)
    at org.javaswift.joss.client.factory.AccountFactory.createAccount(AccountFactory.java:30)
```

I also pulled this from the LOGS

``` java

2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG apache.http.impl.conn.DefaultClientConnection : Sending request: POST /v1/AUTH_wellington/ HTTP/1.1
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "POST /v1/AUTH_wellington/ HTTP/1.1[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "Accept: application/json[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "Content-Length: 108[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "Content-Type: application/json[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "Host: 74.220.148.147:8080[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "Connection: Keep-Alive[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "User-Agent: Apache-HttpClient/4.3.5 (java 1.5)[\r][\n]"
2015-01-27 20:32:49,599 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "[\r][\n]"
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> POST /v1/AUTH_wellington/ HTTP/1.1
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> Accept: application/json
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> Content-Length: 108
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> Content-Type: application/json
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> Host: 74.220.148.147:8080
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> Connection: Keep-Alive
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                       org.apache.http.headers : >> User-Agent: Apache-HttpClient/4.3.5 (java 1.5)
2015-01-27 20:32:49,600 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  >> "{"auth":{"passwordCredentials":{"username":"wellington","password":"wellington"},"tenantName":"wellington"}}"
2015-01-27 20:32:49,647 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "HTTP/1.1 204 No Content[\r][\n]"
2015-01-27 20:32:49,647 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "Server: nginx/1.4.6 (Ubuntu)[\r][\n]"
2015-01-27 20:32:49,647 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "Date: Tue, 27 Jan 2015 20:32:49 GMT[\r][\n]"
2015-01-27 20:32:49,647 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "Content-Type: text/html; charset=UTF-8[\r][\n]"
2015-01-27 20:32:49,647 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "Content-Length: 0[\r][\n]"
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "Connection: keep-alive[\r][\n]"
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "X-Trans-Id: tx058c44e3bf144f22b4348-0054c7f5d2[\r][\n]"
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                          org.apache.http.wire :  << "[\r][\n]"
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG apache.http.impl.conn.DefaultClientConnection : Receiving response: HTTP/1.1 204 No Content
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << HTTP/1.1 204 No Content
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << Server: nginx/1.4.6 (Ubuntu)
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << Date: Tue, 27 Jan 2015 20:32:49 GMT
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << Content-Type: text/html; charset=UTF-8
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << Content-Length: 0
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << Connection: keep-alive
2015-01-27 20:32:49,648 [     qtp966739377-32] DEBUG                       org.apache.http.headers : << X-Trans-Id: tx058c44e3bf144f22b4348-0054c7f5d2
2015-01-27 20:32:49,649 [     qtp966739377-32] DEBUG org.apache.http.impl.client.DefaultHttpClient : Connection can be kept alive indefinitely
2015-01-27 20:32:49,649 [     qtp966739377-32] DEBUG http.impl.conn.PoolingClientConnectionManager : Connection [id: 0][route: {}->http://74.220.148.147:8080] can be kept alive indefinitely
```

**Comment by lebe-dev** [comment]
i have the same problem

i tried few auth-url combinations and auth methods (BASIC \ KEYSTONE) but it doesn't help

**Comment by lebe-dev** [comment]
@SirWellington workaround that works for me:

```
final AccountConfig config = new AccountConfig();

config.setUsername("demo");
config.setPassword("somepasss");
config.setAuthUrl("http://openstack-host:5000/v2.0/tokens");
config.setTenantName("demo");
config.setDisableSslValidation(true);
config.setAuthenticationMethod(AuthenticationMethod.KEYSTONE);

Account account = new ClientImpl(config).authenticate();

final Container container = account.getContainer("some-container-name");

final Collection<StoredObject> storedObjects = container.list("", "", 10000);

for (StoredObject storedObject : storedObjects) {
      System.out.println("- " + storedObject.getName());
}
```

**Comment by ferrys** [comment]
Hi @lebe-dev and @SirWellington, since it seems like this was resolved, I'm going to go ahead and close this issue.
