### ISSUE TITLE
StoredObject.setDeleteAfter casue exception during upload file

### ISSUE THREAD

**Issue by wertzber** [javaswift/joss#91]
Sample code:
 StoredObject object = container.getObject(serverUrl);
 object.setDeleteAfter(TTL_SECONDS);
 object.uploadObject(new File(fileUrlToUpload));

5-12-22 18:49:44,510 ERROR [main              ] [impl.joss.JossFileActions] upload file: D:/git/FileUploadPoc/src/main/resources/images/test.txt failed !!   |TAGS| 
org.javaswift.joss.exception.NotFoundException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_05]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[na:1.8.0_05]
	at org.javaswift.joss.exception.HttpStatusToExceptionMapper.getException(HttpStatusToExceptionMapper.java:48) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.exception.HttpStatusExceptionUtil.getException(HttpStatusExceptionUtil.java:16) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.exception.HttpStatusExceptionUtil.throwException(HttpStatusExceptionUtil.java:10) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.isOk(HttpStatusChecker.java:30) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.command.impl.core.httpstatus.HttpStatusChecker.verifyCode(HttpStatusChecker.java:41) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.command.impl.core.AbstractCommand.call(AbstractCommand.java:50) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.command.impl.core.AbstractSecureCommand.call(AbstractSecureCommand.java:31) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.client.core.AbstractStoredObject.getInfo(AbstractStoredObject.java:259) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.client.core.AbstractObjectStoreEntity.checkForInfo(AbstractObjectStoreEntity.java:98) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.client.core.AbstractObjectStoreEntity.checkForInfo(AbstractObjectStoreEntity.java:89) ~[joss-0.9.7.jar:na]
	at org.javaswift.joss.client.core.AbstractStoredObject.setDeleteAfter(AbstractStoredObject.java:233) ~[joss-0.9.7.jar:na]
	at com.liveperson.fileupload.impl.joss.JossFileActions.uploadFile(JossFileActions.java:34) ~[classes/:na]
	at com.liveperson.fileupload.impl.joss.JossFlow.jossBasicFlow(JossFlow.java:51) [classes/:na]
	at Main.main(Main.java:23) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140) [idea_rt.jar:na]

**Comment by etki** [comment]
I just want to add that i can't set deleteAt before object creation as well (it triggers update request, i guess), while i was hoping there is a chance to save metadata using upload payload headers and do everything in one RTT.
